### PR TITLE
it's libapex now WIP

### PR DESCRIPTION
**Pull request by rminnich**
Should probably rename lib/ap -> lib/apex but that comes later.

Signed-off-by: Ronald G. Minnich rminnich@gmail.com

### CODE REVIEW

**Comment by elbing** [comment]
pdksh is failing due to an "-lap" linking wrong. You can fix it... or we can drop that old shell at all.

**Comment by dancrossnyc** [comment]
Drop it! Pdksh is junk. If we want ksh, we can port David Korn's version.

**Comment by staalmannen** [comment]
mksh worked on 64-bit with the new apex library? Does it have a SIGCHLD
implementation/emulation?
Den 15 maj 2016 14:38 skrev "Dan Cross" <notifications@github.com>:

> Drop it! Pdksh is junk. If we want ksh, we can port David Korn's version.

**Comment by elbing** [comment]
Jens, we're working on apex to have mksh working now (R52c). But we have now problems in dup/pipes. It's being useful to debug apex. But think that apex has a complete stdio from musl, so though in mksh there's almost no differences with your ape pcc port, in other things will be. For example, read about musl stdio extended implementation for sed 4.2.2.

**Comment by elbing** [comment]
Dan, I'm strongly agree with you. Pdksh is still there because we start debugging malloc 64 with it. Now it's useless and old. And doesn't work yet (realloc issues). But it's too old to be considered.

**Comment by elbing** [comment]
With #29 mksh is working like in Plan9 (no differences until posix threads and tty emulation could be done), no prospectwork and unemployed defined. So pdksh must be removed definitively from repo.

**Comment by elbing** [comment]
Obsolete. Renaming the lib will be suggested when native toolchains were working. libapx, libapex...
do we close it for now? it could be an issue to remind us.

**Comment by staalmannen** [comment]
I would love to try to build apex as alternative / replacement of APE on 9front (and put up a package on 9front-ports) using native compilers, but I have not had time to  play with it.

**Pull request closed without merging**
