### PR TITLE
Fixing signals

### PR DESCRIPTION
**Pull request by elbing**
-Adding sigsuspend
-Fixing panic warnings
-WIP signal()

Signed-off-by: Álvaro Jurado <elbingmiss@gmail.com>

### CODE REVIEW

**Comment by elbing** [comment]
Don't run. Kill() suicides with this, though sigsuspend doesn't. And shells still loose some things while are not returning prompt. Incompatible pointer type in signal.c. signal() in posix is defined through sigaction. But in apex we need to deal with envsetup and does signal is not properly returning ints in referred funcs as arguments. Original APE author(s) chose void which breaks the stack with gcc and clang (kenc?). Still investing.

**Comment by elbing** [comment]
In commit message:
```
- signal.h, sys9.h, notetramp.c and signal.c were patched
  for using void args without breaking POSIX. We
  need more things here than Unix for dealing with
  signals.
- Better handling in _envsetup.c, _buf.c, execve.c
- Better handling of _errno.c
- BUG in fwrite was due to rbx problems in crt1.S in past. Removed.
  This solves synchronicity issues in fork, wait and related. Now
  all of them are working properly.
- Some crappy logic in __lockfile.c for stdio until pthreads were
  implemented.

NOT working:
- Sigsuspend never ends in pause(), because no signal
  is catched or is wrongly passed in _envsetup.c.
  Seems notecont can't align u->ip and p->restorepc (line 44 of notetramp.c).
```

**Comment by elbing** [comment]
Also kill() (plan9/kill.c) seems broken due to notecont issue.

**Comment by elbing** [comment]
kill() and pause() are broken, which means there's not sigsuspend yet.

**Comment by bldybuild** [comment]
Commit 5741490a3bbc69baf0c348659393398212ecad7a is not signed-off.

Please fix these issues:

>	1. Álvaro Jurado has not signed-off 5741490.


If you'd like more information on how to sign your commits please visit [signed-off-by.me](https://signed-off-by.me)

**Comment by elbing** [comment]
Ready for being merged. With Harvey #583 signals are working, new sigsuspend is ready:

image

**Pull request merged**
