### PR TITLE
Fixing what is needed to have working gcc

### PR DESCRIPTION
**Pull request by elbing**
Now with musl sources in stdio, __stdio_write
depends on writev in ap/bsd to write to stdout FD
between other things. Traditional version using
_syserrno seems more appropiate than BSD one.

### CODE REVIEW

**Comment by rminnich** [comment]
I don't like either of these implementations.
I don't see why we can't do this:
int writeone(int fd, uint8_t *base, int i)
{
  int tot = 0, amt;
  while (tot < i) {
     amt = write(fd, base+tot, tot-i);
    if (amt < 0)
      return -1; 
   tot += amt;
}
return tot;
}

int writev(int fd, const struct iovec *iov, int iovcnt)
{
  int i, tot = 0, amt;
  for(i = 0; i < iovcnt; i++) {
     amt = writeone(fd, iov[i].iov_base, iov[i].iov_len);
    if (amt < 0) return -1; // writev is a stupid system call b/c you can't tell how much got written.
    tot += amt;
    if (amt < iov[i].iov_len) break;
  }
  return tot;
}

There. no memcpy, no giant 10K array on stack.

Could this work?

**Comment by elbing** [comment]
I'll test it, but for nowI'm rebuilding all stuff to see if gcc finally works, even with sigsetjmp broken.
Note that before that return -1 I'll add _syserrno() for catching the error and translate it (we're in libap, not in a program ported, so this way must be provided).

**Comment by elbing** [comment]
It doesn't, suicides in pwrite in test program.

**Comment by rminnich** [comment]
I don't think that code I sent was write in all details, but It think the overall design is a lot better. Dropping 10K arrays on the stack is almost always  abad idea.

**Comment by elbing** [comment]
I marked as WIP due to incoming read/write wrappers. I think the "error" is not in gcc, is in mksh runtime due to wrong sigprocmask implementation in APEX. This will be here too soon.

**Comment by elbing** [comment]
Pending a better dup2 implementation with  Ron's model over the actual, replacing memcpy.

**Comment by elbing** [comment]
Latest changes in updated commit message, for easy reading:

    Fixing writev for fixing dup2
    
    Now with musl sources in stdio, __stdio_write
      depends on writev in ap/bsd to write to stdout FD
      between other things. Traditional version using
      _syserrno seems more appropiate than BSD one.
    
    Adding _fdinfo control for read/write before calling
      syscalls. This allows native syscalls work with ansi errno
      through __syserrno.
      (in old APE and wrongly removed)
    
    Fixed sigsetjmp, now it's C, it works for now. The code was marked
      as bad in past, but output from gcc or clang seems better than
      old asm approach. I think...
      **This is needed for last patch submitted to mksh branch for Harvey.**
    
    Still needed better version of dup2.
    Still gcc doesn't call as.

**Comment by elbing** [comment]
Ok, this is growing dangerously, but all of this is needed.
Exit codes for APEX programs in harvey never has 0 as success, so gcc can't call as after cc1 if right value is not recorded in pex_run().

In this last commit there are a few regressions, new implementations for chdir and alarm and various fixes. Still WIP.

**Comment by rminnich** [comment]
I think it's time to write a compact regression test that shows the problem.

**Comment by elbing** [comment]
Exec family fixed, tired of warnings. Tested everyone and all working. Nothing to do with non-0 success exit in apex programs. Still investing.

**Comment by elbing** [comment]
GCC is working, but as a canadian cross compiler, so I need to bootstrap it:

	192.168.1.128# bin/rc/sh
	harvey@192.168.1.128:/usr/harvey~$ export PATH=/home/elbing/source/harvey/apex/ports/cross2/bin:$PATH
	harvey@192.168.1.128:/usr/harvey~$ /home/elbing/source/harvey/apex/ports/cross2/bin/gcc-4.7 -std=gnu11 -g -O0 -static -mno-red-zone -D_SUSV2_SOURCE -D_POSIX_SOURCE -D_LIMITS_EXTENSION -D_BSD_SOURCE -D_BSD_EXTENSION -DHAVE_SOCK_OPTS -D_RESEARCH_EXTENSION -DHARVEY -Wall -Wuninitialized -Wmaybe-uninitialized -I/home/elbing/source/harvey/apex/include -c hello.c
	harvey@192.168.1.128:/usr/harvey~$ nm hello.o
	0000000000000000 T main
	                 U puts
	harvey@192.168.1.128:/usr/harvey~$ ld -o hello /home/elbing/source/harvey/apex/amd64/lib/crt1.o /home/elbing/source/harvey/apex/amd64/lib/crti.o /home/elbing/source/harvey/apex/amd64/lib/crtn.o hello.o -L/home/elbing/source/harvey/apex/amd64/lib -L/amd64/lib -lap -lc
	harvey@192.168.1.128:/usr/harvey~$ ./hello
	Hello World!
	harvey@192.168.1.128:/usr/harvey~$

**Comment by elbing** [comment]
This one is the better working writev I have. BSD or GNU versions didn't work at all, and for allowing null in your code, really, it would need at least the half of this. I think the code is fine, those memmove do the trick and giant buffer is gone, re-calculated now through the amount of iov len a la BSD.

**Comment by elbing** [comment]
Tested at all, dup2 working (with BSD and GNU didn't).

**Comment by elbing** [comment]
I forgot freeing the buf at the end.

**Comment by elbing** [comment]
LGTM

**Pull request merged**
