### PR TITLE
Adding stdio_ext

### PR DESCRIPTION
**Pull request by elbing**
Tested with GNU sed 4.2.2

Change-Id: I8e27397377bd4b1da45da7ad6fe51eed7b2d8e94

### CODE REVIEW

**Comment by elbing** [comment]
With this code we have gnu sed and m4. Less steps to minimal essentials for native toolchain.

**Comment by elbing** [comment]
none? lgtm myself?

**Comment by rminnich** [comment]
I wonder why we need weak but it's gnu so ...

LGTM

**Comment by elbing** [comment]
Due to keep original code as possible. It hasn't any effect for now. Most of them are for arch differences and internals references. Since it's pending the task for separating arch dependent headers (amd64/include/bits future dir) and its implications on libs code, for now doesn't matter. It's the major next step with posix threads implementation.

Next PR: new regex and dirent code (gnu make port in progress).

**Pull request merged**
